### ISSUE TITLE
Afschrijving termijnbedrag rekening houden met transacties

### ISSUE THREAD

**Issue by WesMaster** [WesMaster/MoneyGrip#128]
Transacties met de afschrijving gekoppeld moeten afgetrokken worden van het 'openstaande' bedrag. Het bedrag per maand moet daarop aangepast worden.

Dit speelt wanneer er bijv. kosten gemaakt zijn voor een auto. Deze kosten worden betaald met het geld dat staat gereserveerd voor de afschrijving. Om nog op de gewenste datum het ingestelde bedrag te bereiken zal het bedrag per maand omhoog moeten.

**Comment by Wesmaster** [comment]
Dit wordt opgelost door het totaalbedrag tegenover het aanwezige bedrag op de rekening te zetten. Het tekort wordt verrekend over alle afschrijvingen. Hierdoor hoeven transacties niet bekeken worden.
